[project]
name = "fifo-dev-common"
version = "0.1.0a0"
description = "Core Python utilities shared across all fifo-dev repositories"
authors = [
  { name = "Florent Gastoud" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pyserial-asyncio",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pytest-asyncio",
  "trustme",           #  for generating self‑signed TLS certificates during tests
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=fifo_dev_common"

[tool.coverage.run]
branch = true
concurrency = ["multiprocessing"]
source = ["fifo_dev_common"]

[tool.coverage.report]
omit = ["tests/*"]

[[tool.mypy.overrides]]
module = [
  "serial_asyncio",
]
follow_untyped_imports = true